from dataclasses import dataclass

from fdt.vehicle.tyre_model import TyreModel


@dataclass(frozen=True)
class AxleForceResult:
    """Forces generated by the two tyres on an axle."""

    left_longitudinal_force: float
    left_lateral_force: float
    right_longitudinal_force: float
    right_lateral_force: float
    total_longitudinal_force: float
    total_lateral_force: float


class AxleTyreModel:
    """Calculate the combined tyre forces generated by an axle."""

    def __init__(self, tyre_model: TyreModel) -> None:
        self.tyre_model = tyre_model

    def calculate_forces(
        self,
        axle_vertical_load: float,
        left_slip_ratio: float,
        left_slip_angle: float,
        right_slip_ratio: float,
        right_slip_angle: float,
    ) -> AxleForceResult:
        """Calculate left, right, and total axle tyre forces."""

        if axle_vertical_load <= 0:
            raise ValueError("Axle vertical load must be positive.")

        left_vertical_load = axle_vertical_load / 2.0
        right_vertical_load = axle_vertical_load / 2.0

        left_force = self.tyre_model.calculate_forces(
            vertical_load=left_vertical_load,
            slip_ratio=left_slip_ratio,
            slip_angle=left_slip_angle,
        )

        right_force = self.tyre_model.calculate_forces(
            vertical_load=right_vertical_load,
            slip_ratio=right_slip_ratio,
            slip_angle=right_slip_angle,
        )

        total_longitudinal_force = (
            left_force.longitudinal_force
            + right_force.longitudinal_force
        )

        total_lateral_force = (
            left_force.lateral_force
            + right_force.lateral_force
        )

        return AxleForceResult(
            left_longitudinal_force=left_force.longitudinal_force,
            left_lateral_force=left_force.lateral_force,
            right_longitudinal_force=right_force.longitudinal_force,
            right_lateral_force=right_force.lateral_force,
            total_longitudinal_force=total_longitudinal_force,
            total_lateral_force=total_lateral_force,
        )