from dataclasses import dataclass

from fdt.vehicle.parameters import TireParameters


@dataclass(frozen=True)
class TyreForceResult:
    """Forces generated by a tyre."""

    longitudinal_force: float
    lateral_force: float


class TyreModel:
    """Simplified linear tyre model with friction-circle limitation."""

    def __init__(self, parameters: TireParameters) -> None:
        self.parameters = parameters

    def calculate_forces(
        self,
        vertical_load: float,
        slip_ratio: float,
        slip_angle: float,
    ) -> TyreForceResult:
        """Calculate longitudinal and lateral tyre forces."""

        if vertical_load <= 0:
            raise ValueError("Vertical load must be positive.")

        longitudinal_stiffness = (
            self.parameters.longitudinal_stiffness.value
        )

        lateral_stiffness = (
            self.parameters.lateral_stiffness.value
        )

        friction_coefficient = (
            self.parameters.friction_coefficient.value
        )

        if longitudinal_stiffness is None:
            raise ValueError(
                "Longitudinal tyre stiffness is required."
            )

        if lateral_stiffness is None:
            raise ValueError(
                "Lateral tyre stiffness is required."
            )

        if friction_coefficient is None:
            raise ValueError(
                "Tyre friction coefficient is required."
            )

        if friction_coefficient <= 0:
            raise ValueError(
                "Tyre friction coefficient must be positive."
            )

        longitudinal_force = (
            longitudinal_stiffness * slip_ratio
        )

        lateral_force = (
            -lateral_stiffness * slip_angle
        )

        maximum_force = friction_coefficient * vertical_load

        total_force = (
            longitudinal_force**2
            + lateral_force**2
        ) ** 0.5

        if total_force > maximum_force:
            scale = maximum_force / total_force

            longitudinal_force *= scale
            lateral_force *= scale

        return TyreForceResult(
            longitudinal_force=longitudinal_force,
            lateral_force=lateral_force,
        )